import { LegalPage } from "@/components/legal-page";

export default function PrivacyPage() {
	return <LegalPage title="Privacy"><p>Last updated September 20, 2026.</p>
		{!process.env.PUBLIC_PUBLISHER_NAME && <p role="alert">Launch draft: publisher and support contact details must be added before public release.</p>}
		<section><h2>On your devices</h2><p>Your pages are saved in this browser or on your iPhone. App selections, your saved location, Health inputs, and detailed behavior progress stay on your iPhone. Pocketwork asks for the permissions needed by the blocks you choose. You can revoke them in iPhone Settings. Turning off permissions can stop a routine from working.</p></section>
		<section><h2>When you sign in</h2><p>Supabase stores your account identifier, email address if supplied by Apple or Google, page definitions, and app-group names so you can sync. Text you put into a page is part of its definition, so avoid placing sensitive information there. If you enable Share status, your phone also uploads running-session status, remaining allowance, and up to 30 days of minute counts. It does not upload app identities or location coordinates.</p><p>Vercel hosts the website and account service; Supabase provides authentication and cloud storage. These services process request information, such as IP addresses, for delivery and security. Pocketwork does not use advertising trackers or sell your data.</p></section>
		<section><h2>Agents and purchases</h2><p>MCP lets an agent you connect read and change your cloud pages and read status you opted to share. Only share the private connection token with an agent you trust. Its provider has its own privacy practices. Pocketwork does not send your pages to an AI provider by itself.</p><p>Apple handles in-app payments. We store subscription transaction identifiers, your linked account ID, and subscription status to verify Pro access. We do not receive card details.</p></section>
		<section><h2>Retention and deletion</h2><p>Account data remains until you delete it. Delete account in Account to remove your cloud data and revoke linked Apple sign-in. Local copies and exported files on other devices are not remotely erased; remove those separately. Service backups may retain deleted data until their normal retention expires. Apple keeps its purchase records separately. Temporary Apple deletion handshakes expire after ten minutes and are removed when used or when the account is deleted.</p><p>Deleting an account does not cancel an Apple subscription. Manage it in your Apple account.</p></section>
		<section><h2>Contact</h2><p>{process.env.PUBLIC_PUBLISHER_NAME || "Publisher details pending."} {process.env.PUBLIC_SUPPORT_EMAIL ? <a href={`mailto:${process.env.PUBLIC_SUPPORT_EMAIL}`}>{process.env.PUBLIC_SUPPORT_EMAIL}</a> : "Support email pending."}</p></section>
	</LegalPage>;
}
