"use client";
import { default_fields, health_metrics } from "@/lib/builder-blocks";
import type { BehaviorConfig } from "@/lib/behaviors";
import type { LogicNode } from "@/lib/logic-graph";
import { Button } from "./ui";
export function BuilderSettings({ node, patch }: { node: LogicNode; patch: (config: Partial<BehaviorConfig>) => void }) {
	const c = node.config!; const fields = c.fields ?? default_fields;
	return <>
		{["number_input", "progress"].includes(node.kind) && <label>{node.kind === "progress" ? "Target" : "Initial value"}<input type="number" value={c.value} onChange={e => patch({ value: Number(e.target.value) })} /></label>}
		{["text_input", "text_compare"].includes(node.kind) && <label>{node.kind === "text_input" ? "Initial text" : "Match text"}<input value={c.text ?? ""} maxLength={240} onChange={e => patch({ text: e.target.value })} /></label>}
		{["calculate", "aggregate", "text_compare"].includes(node.kind) && <label>Operation<select value={c.operation ?? (node.kind === "calculate" ? "add" : node.kind === "aggregate" ? "sum" : "equals")} onChange={e => patch({ operation: e.target.value as BehaviorConfig["operation"] })}>{(node.kind === "calculate" ? ["add", "subtract", "multiply", "divide"] : node.kind === "aggregate" ? ["sum", "average", "minimum", "maximum", "count"] : ["equals", "contains", "starts_with"]).map(op => <option key={op} value={op}>{op.replaceAll("_", " ")}</option>)}</select></label>}
		{["aggregate", "chart"].includes(node.kind) && <label>Numeric field ID<input value={c.field ?? "value"} maxLength={32} onChange={e => patch({ field: e.target.value })} /></label>}
		{node.kind === "health" && <><label>Metric<select value={c.metric ?? "steps"} onChange={e => patch({ metric: e.target.value as BehaviorConfig["metric"] })}>{health_metrics.map(metric => <option key={metric} value={metric}>{metric.replaceAll("_", " ")}</option>)}</select></label><p>Read-only Apple Health access on iPhone. Refresh while the routine is open. Missing data remains unavailable.</p></>}
		{node.kind === "app_gate" && <><label>App groups, comma-separated<input value={(c.groups ?? []).join(", ")} onChange={e => patch({ groups: e.target.value.split(",").map(s => s.trim()).filter(Boolean) })} /></label><p>Closed = block these groups. Open releases this gate only; other app restrictions still apply. Choose each group's apps privately on your phone.</p></>}
		{node.kind === "add_allowance" && <><label>Minutes to add<input type="number" min="1" max="1440" value={c.minutes} onChange={e => patch({ minutes: Number(e.target.value) })} /></label><p>Grants once per day to the active home allowance. The location and allowed windows still apply.</p></>}
		{node.kind === "save_entry" && <p>Keeps the latest 200 entries on this device. Connect clear to a button if you want to reset this data.</p>}
		{node.kind === "form" && <fieldset className="builder-fields"><legend>Fields</legend>{fields.map((field, index) => <div key={index}><label>Field name<input value={field.label} maxLength={80} onChange={e => patch({ fields: fields.map((f,i) => i === index ? { ...f, label: e.target.value } : f) })} /></label><label>Field ID<input value={field.id} maxLength={32} onChange={e => patch({ fields: fields.map((f,i) => i === index ? { ...f, id: e.target.value } : f) })} /></label><label>Type<select value={field.type} onChange={e => patch({ fields: fields.map((f,i) => i === index ? { ...f, type: e.target.value as typeof field.type } : f) })}><option value="number">Number</option><option value="text">Text</option><option value="boolean">Checkbox</option></select></label><label><input type="checkbox" checked={field.required} onChange={e => patch({ fields: fields.map((f,i) => i === index ? { ...f, required: e.target.checked } : f) })} />Required</label><Button disabled={fields.length === 1} onClick={() => patch({ fields: fields.filter((_,i) => i !== index) })}>Remove field</Button></div>)}<Button disabled={fields.length >= 8} onClick={() => { let id = fields.length+1; while (fields.some(f => f.id === `field_${id}`)) { id++; } patch({ fields: [...fields,{ id: `field_${id}`, label: "New field", type: "number", required: true }] }); }}>Add field</Button></fieldset>}
	</>;
}
