"use client";
import { useEffect, useState } from "react";
import { LogicCanvas } from "./logic-canvas";
import type { AppDocument } from "@/lib/document";
import { Button, SectionLabel } from "./ui";
const days = ["", "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
export function HomeAllowance({ document, on_back, on_save, disabled = false }: { document: AppDocument; on_back: () => void; on_save: (document: AppDocument) => void; disabled?: boolean }) {
	const [dirty, set_dirty] = useState(false);
	function leave() { if (!dirty || window.confirm("Discard unapplied graph changes?")) { on_back(); } }
	const [view, set_view] = useState<"page" | "logic">("page");
	useEffect(() => { if (new URLSearchParams(window.location.search).get("view") === "logic") { set_view("logic"); } }, []);
	return <main className="workbench home"><header className="topbar"><Button onClick={leave}>My routines</Button><strong>{document.name}</strong></header><div className="canvas-toolbar"><div className="view-tabs" role="tablist" aria-label="Editor view"><button type="button" role="tab" aria-selected={view === "page"} onClick={() => set_view("page")}>Page</button><button type="button" role="tab" aria-selected={view === "logic"} onClick={() => set_view("logic")}>Logic</button></div></div><div hidden={view !== "logic"}><LogicCanvas document={document} on_change={on_save} disabled={disabled} on_dirty_change={set_dirty} /></div><section hidden={view !== "page"} className="home-section"><SectionLabel number="01">HOME ALLOWANCE</SectionLabel><h1>{document.name}</h1><p className="supporting">Only distraction use at home counts. The daily allowance is shared across all windows and resets at midnight in Los Angeles. Outside these windows, distractions are blocked at home.</p><ul className="group-list">{document.home_allowance?.rules.map((rule) => <li className="tool-card" key={rule.days.join()}><div className="tool-body"><strong>{rule.days.map((day) => days[day]).join(", ")}: {rule.allowance_minutes} minutes total</strong><span>{rule.windows.map((window) => `${window.start}–${window.end}`).join(" and ")}</span></div></li>)}</ul><h2>Finish on your iPhone</h2><p className="supporting">Update Pocketwork, open this routine, choose Distractions, and tap Set home here while you are home. Then enable it. Your location and app selections stay on the phone.</p><p className="supporting">{document.enabled ? "Enabled on your account. Open the phone app to apply changes." : "Saved to your library. Setup is required before this can run."}</p><p className="supporting">Usage is checkpointed in whole minutes. Leaving home can leave the last partial minute uncounted; location changes and Screen Time callbacks may be delayed by iOS.</p></section></main>;
}
