"use client";

import type { BehaviorConfig } from "@/lib/behaviors";
import type { LogicGraph, LogicNode } from "@/lib/logic-graph";
import { ALL_DAYS, DAY_LABELS } from "@/lib/schedule";
import { InlineText, NumberField } from "./creation-controls";

export function PrimitiveSettings({ node, graph, patch }: { node: LogicNode; graph: LogicGraph; patch: (patch: Partial<BehaviorConfig>) => void }) {
	const config = node.config!;
	const connected = (input: string) => graph.connections.some(edge => edge.to === node.id && edge.input === input);
	return <>
		{node.kind === "variable" && <><NumberField label="Starting value" value={config.value} min={-1000000} max={1000000} integer={false} on_commit={value => patch({ value })} /><label className="connection-field"><span>Unit (optional)</span><InlineText label="Variable unit" value={config.unit ?? ""} placeholder="minutes, points, sessions…" max_length={24} on_commit={unit => patch({ unit })} /></label><p className="connection-help">A value you own, not measured app usage. Add a Change variable action to set, add, subtract, or reset it.</p></>}
		{node.kind === "change_value" && <><label className="connection-field"><span>Change which variable?</span><select aria-label="Variable to change" value={config.variable_id ?? ""} onChange={event => patch({ variable_id: event.target.value || undefined })}><option value="">Choose a variable…</option>{graph.nodes.filter(item => item.kind === "variable").map(item => <option key={item.id} value={item.id}>{item.config?.label || "Variable"}</option>)}</select></label><label className="connection-field"><span>Action</span><select aria-label="Variable action" value={config.change ?? "add"} onChange={event => patch({ change: event.target.value as BehaviorConfig["change"] })}><option value="add">Add</option><option value="subtract">Subtract</option><option value="set">Set to</option><option value="reset">Reset to starting value</option></select></label>{config.change !== "reset" && !connected("amount") && <NumberField label="Amount" value={config.value} min={-1000000} max={1000000} integer={false} on_commit={value => patch({ value })} />}<p className="connection-help">Runs once for each event, or when a condition becomes true. Staying true does not keep adding. Several actions on one variable run in page connection order. No daily reward policy is assumed.</p></>}
		{node.kind === "elapsed_timer" && <><label className="connection-field"><span>Mode</span><select aria-label="Timer mode" value={config.timer_mode ?? "countdown"} onChange={event => patch({ timer_mode: event.target.value as BehaviorConfig["timer_mode"], value: Math.max(1 / 60, config.value) })}><option value="countdown">Count down</option><option value="stopwatch">Count up</option></select></label>{config.timer_mode !== "stopwatch" && !connected("duration") && <NumberField label="Duration" value={config.value} min={1 / 60} max={10080} integer={false} unit="minutes" on_commit={value => patch({ value })} />}<p className="connection-help">Start, pause, stop, and reset on the page, or connect events. Stop and countdown completion emit Finished. Outputs use minutes. Nothing is blocked automatically. Duration is captured when a new countdown starts.</p></>}
		{node.kind === "time_window" && <><div className="document-time-fields"><label>From<input type="time" aria-label="Window starts" value={config.time} onChange={event => { if (event.target.value) { patch({ time: event.target.value }); } }} /></label><label>Until<input type="time" aria-label="Window ends" value={config.end_time ?? "20:00"} onChange={event => { if (event.target.value) { patch({ end_time: event.target.value }); } }} /></label></div><div className="day-picker" role="group" aria-label="Window days">{ALL_DAYS.map(day => <button type="button" aria-pressed={config.days.includes(day)} key={day} onClick={() => { const days = config.days.includes(day) ? config.days.filter(value => value !== day) : [...config.days, day].sort(); if (days.length) { patch({ days }); } }}>{DAY_LABELS[day - 1]}</button>)}</div><p className="connection-help">Uses the device's local time. Earlier end times cross midnight. This is only a condition; connect it to decide what happens.</p></>}
	</>;
}
