"use client";

import { useState } from "react";
import { ArrowDown, ArrowUp, ChevronDown, GripVertical, Plus, Smartphone, Trash2 } from "lucide-react";
import { describe_shield, move_block, new_id, shield_mode, type AppDocument, type Block } from "@/lib/document";
import { connected_summary, node_name, page_kinds, remove_page_block } from "@/lib/creation";
import { graph_from_document } from "@/lib/logic-graph";
import { ALL_DAYS, DAY_LABELS, WEEKDAYS } from "@/lib/schedule";
import type { AppGroup } from "@/lib/library";
import { BlockIcon, InlineText, NumberField } from "./creation-controls";
import { Button, Toggle } from "./ui";

export function RoutinePage({ document, groups, on_change, on_add, on_connect, on_error }: { document: AppDocument; groups: AppGroup[]; on_change: (document: AppDocument) => void; on_add: (before?: string) => void; on_connect: (id?: string) => void; on_error: (message: string) => void }) {
	const [menu, set_menu] = useState<string | null>(null);
	const [dragged, set_dragged] = useState<string | null>(null);
	const graph = graph_from_document(document);
	function update(block: Block) { on_change({ ...document, blocks: document.blocks.map(item => item.id === block.id ? block : item) }); }
	function remove(id: string) { try { on_change(remove_page_block(document, id)); set_menu(null); } catch (error) { on_error(error instanceof Error ? error.message : "Could not remove this block."); } }
	function drop(id: string) {
		if (!dragged || dragged === id) { return; }
		const blocks = [...document.blocks]; const from = blocks.findIndex(block => block.id === dragged); const to = blocks.findIndex(block => block.id === id);
		if (from >= 0 && to >= 0) { const [block] = blocks.splice(from, 1); blocks.splice(to, 0, block); on_change({ ...document, blocks }); }
		set_dragged(null);
	}
	return <div className="routine-document">
		<div className="document-sigil" aria-hidden="true"><BlockIcon kind="note" /></div>
		<h1 className="document-title" aria-label={document.name}><InlineText label="Page name" value={document.name} required placeholder="Untitled page" on_commit={name => on_change({ ...document, name })} /></h1>
		<InlineText label="Description" value={document.description} placeholder="Add a description…" max_length={200} on_commit={description => on_change({ ...document, description })} className="document-description" />
		<div className="document-properties"><span><Smartphone />{document.blocks.some(block => block.type === "schedule") ? "Scheduled on iPhone" : document.blocks.some(block => block.type === "timer") ? "Start when you need it" : "Your own little tool"}</span>{document.behaviors?.nodes.length ? <button type="button" onClick={() => on_connect()}>{document.behaviors.nodes.length} connected blocks <ChevronDown /></button> : <span>Changes save automatically</span>}</div>
		<ol className="document-blocks" aria-label="Page blocks">{document.blocks.map((block, index) => <li key={block.id} className="document-row" data-block-id={block.id} onDragOver={event => { if (dragged) { event.preventDefault(); } }} onDrop={() => drop(block.id)}>
			<div className="block-gutter"><button type="button" aria-label={`Insert before ${block.title}`} onClick={() => on_add(block.id)}><Plus /></button><button type="button" draggable aria-label={`Actions for ${block.title}`} aria-expanded={menu === block.id} onDragStart={event => { set_dragged(block.id); event.dataTransfer.setData("text/plain", block.id); }} onDragEnd={() => set_dragged(null)} onClick={() => set_menu(menu === block.id ? null : block.id)}><GripVertical /></button></div>
			{menu === block.id && <div className="block-action-menu" onKeyDown={event => { if (event.key === "Escape") { set_menu(null); } }}><Button variant="quiet" disabled={index === 0} onClick={() => { on_change(move_block(document, block.id, -1)); set_menu(null); }}><ArrowUp />Move up</Button><Button variant="quiet" disabled={index === document.blocks.length - 1} onClick={() => { on_change(move_block(document, block.id, 1)); set_menu(null); }}><ArrowDown />Move down</Button><Button variant="danger" onClick={() => remove(block.id)}><Trash2 />Remove block</Button></div>}
			<NativeBlock block={block} document={document} groups={groups} on_change={update} on_document={on_change} on_add={() => on_add(block.id)} />
		</li>)}</ol>
		{document.behaviors?.nodes.filter(node => page_kinds.has(node.kind)).map(node => <section className="connected-page-block" key={node.id}>
			<div className="connected-page-heading"><BlockIcon kind={node.kind} /><strong>{node.config.label || node.kind}</strong><Button variant="quiet" onClick={() => on_connect(node.id)}>Configure</Button></div>
			<p className="supporting">{connected_summary(graph, node)}</p>
			{node.kind === "chart" || node.kind === "table" ? <div className="data-placeholder"><BlockIcon kind={node.kind} /><span>Your {node.kind} will show saved entries.<small>Use Preview to test with sample entries of your own.</small></span></div> : node.kind === "progress" ? <div className="data-placeholder"><span>Target: {node.config.value}<small>Uses your connected value. No test data yet.</small></span></div> : <span className="connected-kind">{node.kind === "form" ? `${node.config.fields?.length ?? 1} input field${(node.config.fields?.length ?? 1) === 1 ? "" : "s"}` : node_name(node)}</span>}
		</section>)}
		<button type="button" className="document-add" onClick={() => on_add()}><Plus /><span>Add a block</span><kbd aria-hidden="true">/</kbd></button>
		<div className="document-bottom-note">Start simple. Add a timer, a log, or something you want to see.</div>
	</div>;
}

function NativeBlock({ block, document, groups, on_change, on_document, on_add }: { block: Block; document: AppDocument; groups: AppGroup[]; on_change: (block: Block) => void; on_document: (document: AppDocument) => void; on_add: () => void }) {
	const [new_group, set_new_group] = useState("");
	const title = <InlineText label={`Block title: ${block.title}`} value={block.title} required on_commit={title => on_change({ ...block, title })} className="block-title-input" />;
	if (block.type === "note") { return <div className="document-text-block">{block.title !== "Text" && title}<InlineText label={`Text: ${block.title}`} value={block.text} multiline max_length={1000} placeholder="Write something, or press / to add a block…" on_commit={text => on_change({ ...block, text })} on_slash={on_add} /></div>; }
	if (block.type === "heading") { return <div className="document-heading-block">{title}<InlineText label={`Supporting text: ${block.title}`} value={block.subtitle} placeholder="Add supporting text…" max_length={200} on_commit={subtitle => on_change({ ...block, subtitle })} /></div>; }
	if (block.type === "checklist") { return <div className="document-checklist">{title}{block.items.map((item, index) => <div className="document-task" key={item.id}><span className="empty-checkbox" aria-hidden="true" /><InlineText label={`Task ${index + 1}: ${block.title}`} value={item.text} required placeholder="To-do" on_commit={text => on_change({ ...block, items: block.items.map(entry => entry.id === item.id ? { ...entry, text } : entry) })} /><Button variant="quiet" aria-label={`Remove task ${index + 1}: ${block.title}`} disabled={block.items.length === 1} onClick={() => on_change({ ...block, items: block.items.filter(entry => entry.id !== item.id) })}><Trash2 /></Button></div>)}<Button variant="quiet" disabled={block.items.length >= 20} onClick={() => on_change({ ...block, items: [...block.items, { id: new_id(), text: "New task" }] })}><Plus />Add task</Button></div>; }
	return <section className="document-capability"><div className="capability-title"><BlockIcon kind={block.type} />{title}</div>
		{block.type === "timer" && <><NumberField label="Session length" value={block.minutes} min={15} max={120} unit="minutes" on_commit={minutes => on_change({ ...block, minutes })} /><p className="supporting">Starts when you press Start. Ends when the timer finishes or you stop it.</p><details className="document-details"><summary>Session options</summary><Toggle label="Notify on completion" description="A notification on your iPhone" checked={document.rules.notify_on_complete} on_change={notify_on_complete => on_document({ ...document, rules: { ...document.rules, notify_on_complete } })} /></details></>}
		{block.type === "counter" && <NumberField label="Target" value={block.target} min={1} max={1000} on_commit={target => on_change({ ...block, target })} />}
		{block.type === "schedule" && <><div className="day-picker" role="group" aria-label="Days of the week">{ALL_DAYS.map(day => <button type="button" key={day} aria-pressed={block.days.includes(day)} onClick={() => { const days = block.days.includes(day) ? block.days.filter(value => value !== day) : [...block.days, day].sort(); if (days.length) { on_change({ ...block, days }); } }}>{DAY_LABELS[day - 1]}</button>)}</div><div className="document-inline-actions"><Button variant="quiet" onClick={() => on_change({ ...block, days: WEEKDAYS })}>Weekdays</Button><Button variant="quiet" onClick={() => on_change({ ...block, days: ALL_DAYS })}>Every day</Button></div><div className="document-time-fields"><label>From<input type="time" aria-label="Starts" value={block.start} onChange={event => { if (event.target.value) { on_change({ ...block, start: event.target.value }); } }} /></label><span>to</span><label>Until<input type="time" aria-label="Ends" value={block.end} onChange={event => { if (event.target.value) { on_change({ ...block, end: event.target.value }); } }} /></label></div><p className="supporting">Repeats while enabled on your iPhone. Outside this window, this routine releases its restrictions. An earlier end time means the next day.</p><span className="capability-state">{document.enabled ? "Enabled on your account" : "Off until you enable it on your iPhone"}</span></>}
		{block.type === "screen_time" && <><label className="document-select"><span>What happens</span><select aria-label="App blocking mode" value={shield_mode(block)} onChange={event => { const mode = event.target.value as "block" | "allow_only" | "limit"; on_change({ ...block, mode, groups: mode !== "block" && !block.groups?.length ? [groups[0]?.name ?? "Distractions"] : block.groups, limit_minutes: mode === "limit" ? block.limit_minutes ?? 30 : undefined }); }}><option value="block">Block these apps</option><option value="allow_only">Allow only these apps</option><option value="limit">Give these apps a time limit</option></select></label>{shield_mode(block) === "limit" && <NumberField label="Minutes before blocking" value={block.limit_minutes ?? 30} min={15} max={1440} unit="minutes" on_commit={limit_minutes => on_change({ ...block, limit_minutes })} />}
			<div className="document-group-picks" role="group" aria-label="App groups">{[...new Set([...groups.map(group => group.name), ...(block.groups ?? [])])].map(name => <label key={name}><input type="checkbox" checked={(block.groups ?? []).some(value => value.toLowerCase() === name.toLowerCase())} onChange={event => on_change({ ...block, groups: event.target.checked ? [...(block.groups ?? []), name] : (block.groups ?? []).filter(value => value.toLowerCase() !== name.toLowerCase()) })} />{name}</label>)}</div>
			<details className="document-details"><summary>Add an app group</summary><form className="document-inline-actions" onSubmit={event => { event.preventDefault(); const name = new_group.trim(); if (name && !(block.groups ?? []).some(value => value.toLowerCase() === name.toLowerCase())) { on_change({ ...block, groups: [...(block.groups ?? []), name] }); set_new_group(""); } }}><input aria-label="New group name" placeholder="Social, games, work…" maxLength={40} value={new_group} onChange={event => set_new_group(event.target.value)} /><Button type="submit" disabled={!new_group.trim()}>Add group</Button></form></details>
			<p className="supporting">{describe_shield(block)}. Choose the actual apps privately on your iPhone.</p><p className="capability-state">{document.rules.block_during_focus ? `Applies only while your ${document.blocks.some(item => item.type === "schedule") ? "schedule is active" : "focus timer is running"}.` : "Not connected to blocking yet."}</p>{!document.rules.block_during_focus && document.blocks.some(item => item.type === "timer" || item.type === "schedule") && <Button onClick={() => on_document({ ...document, rules: { ...document.rules, block_during_focus: true } })}>Enable blocking during this routine</Button>}
		</>}
	</section>;
}
